# Generated by Django 4.2.1 on 2023-05-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('subtitulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('Autor', models.CharField(max_length=64)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FrutosSecos',
        ),
        migrations.DeleteModel(
            name='Sucursales',
        ),
        migrations.DeleteModel(
            name='Vinos',
        ),
    ]
